/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as adminADashboardRouteImport } from './routes/(admin)/a/_dashboard'
import { Route as adminAAuthRouteImport } from './routes/(admin)/a/_auth'
import { Route as adminADashboardIndexRouteImport } from './routes/(admin)/a/_dashboard/index'
import { Route as adminAAuthLoginRouteImport } from './routes/(admin)/a/_auth/login'

const adminARouteImport = createFileRoute('/(admin)/a')()

const adminARoute = adminARouteImport.update({
  id: '/(admin)/a',
  path: '/a',
  getParentRoute: () => rootRouteImport,
} as any)
const adminADashboardRoute = adminADashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => adminARoute,
} as any)
const adminAAuthRoute = adminAAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => adminARoute,
} as any)
const adminADashboardIndexRoute = adminADashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminADashboardRoute,
} as any)
const adminAAuthLoginRoute = adminAAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => adminAAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/a': typeof adminADashboardRouteWithChildren
  '/a/login': typeof adminAAuthLoginRoute
  '/a/': typeof adminADashboardIndexRoute
}
export interface FileRoutesByTo {
  '/a': typeof adminADashboardIndexRoute
  '/a/login': typeof adminAAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)/a': typeof adminARouteWithChildren
  '/(admin)/a/_auth': typeof adminAAuthRouteWithChildren
  '/(admin)/a/_dashboard': typeof adminADashboardRouteWithChildren
  '/(admin)/a/_auth/login': typeof adminAAuthLoginRoute
  '/(admin)/a/_dashboard/': typeof adminADashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/a' | '/a/login' | '/a/'
  fileRoutesByTo: FileRoutesByTo
  to: '/a' | '/a/login'
  id:
    | '__root__'
    | '/(admin)/a'
    | '/(admin)/a/_auth'
    | '/(admin)/a/_dashboard'
    | '/(admin)/a/_auth/login'
    | '/(admin)/a/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminARoute: typeof adminARouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)/a': {
      id: '/(admin)/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof adminARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/a/_dashboard': {
      id: '/(admin)/a/_dashboard'
      path: ''
      fullPath: '/a'
      preLoaderRoute: typeof adminADashboardRouteImport
      parentRoute: typeof adminARoute
    }
    '/(admin)/a/_auth': {
      id: '/(admin)/a/_auth'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof adminAAuthRouteImport
      parentRoute: typeof adminARoute
    }
    '/(admin)/a/_dashboard/': {
      id: '/(admin)/a/_dashboard/'
      path: '/'
      fullPath: '/a/'
      preLoaderRoute: typeof adminADashboardIndexRouteImport
      parentRoute: typeof adminADashboardRoute
    }
    '/(admin)/a/_auth/login': {
      id: '/(admin)/a/_auth/login'
      path: '/login'
      fullPath: '/a/login'
      preLoaderRoute: typeof adminAAuthLoginRouteImport
      parentRoute: typeof adminAAuthRoute
    }
  }
}

interface adminAAuthRouteChildren {
  adminAAuthLoginRoute: typeof adminAAuthLoginRoute
}

const adminAAuthRouteChildren: adminAAuthRouteChildren = {
  adminAAuthLoginRoute: adminAAuthLoginRoute,
}

const adminAAuthRouteWithChildren = adminAAuthRoute._addFileChildren(
  adminAAuthRouteChildren,
)

interface adminADashboardRouteChildren {
  adminADashboardIndexRoute: typeof adminADashboardIndexRoute
}

const adminADashboardRouteChildren: adminADashboardRouteChildren = {
  adminADashboardIndexRoute: adminADashboardIndexRoute,
}

const adminADashboardRouteWithChildren = adminADashboardRoute._addFileChildren(
  adminADashboardRouteChildren,
)

interface adminARouteChildren {
  adminAAuthRoute: typeof adminAAuthRouteWithChildren
  adminADashboardRoute: typeof adminADashboardRouteWithChildren
}

const adminARouteChildren: adminARouteChildren = {
  adminAAuthRoute: adminAAuthRouteWithChildren,
  adminADashboardRoute: adminADashboardRouteWithChildren,
}

const adminARouteWithChildren =
  adminARoute._addFileChildren(adminARouteChildren)

const rootRouteChildren: RootRouteChildren = {
  adminARoute: adminARouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
